loglevel: debug
http_server: 
  port: 8091
http_client: 
  skipSSL: true # This is currently broken
  timeout: 30 # http client timeout
  period: 10 # How often to scan a URL. In seconds.
mongo_client:
  host: localhost
  port: 27017
  username: root # This is currently broken
  password: example  # http client timeout
  userDatabase: users
  accountDatabase: accounts 
urls:
  - https://google.com
  - http://facebook.com
  # - https://amazon.com
  # - http://ebay.com
  # - http://fake.local # This fake domain
